### ISSUE TITLE
Feature request: get access to media property of image

### ISSUE THREAD

**Issue by jimblue** [OleVik/grav-plugin-imgcaptions#15]
Hi @OleVik !

Thanks again for the major update with template, I love it.

I just miss access to media property from Grav.

Especially width and height.

It's particularly usefull when lazy-loading image to calculate parent div padding.

Is there any way to access those information with the present release?

If not could you make some magic?

Cheers and happy new year by advance!

**Comment by jimblue** [comment]
Hey @OleVik !

Did you had a chance to read this?

**Comment by OleVik** [comment]
I've been swamped with work, so have not had a chance. The work I've done on ImgCaptions has largely been optimizing new regular expressions. I would not mind a PR though, if anyone is working on something like it.

**Comment by OleVik** [comment]
I've assigned this to the v3 milestone, as it would require a comprehensive refactor to allow the flexibility and strength of the current implementation.

**Comment by jimblue** [comment]
Hey @OleVik ! How are you?

I was wondering if you found a way to solve this issue. And if you do how we could help to give a boost for v3 milestone?

Cheers

**Comment by OleVik** [comment]
I've not had the time to do a refactor, and given the way in which I've written this plugin it might be more easily accomplished with its [Sister Plugin](https://github.com/trilbymedia/grav-plugin-image-captions).

**Comment by OleVik** [comment]
@jimblue, it's been quite a while since this request originally opened, but I've recently had the time to do a refactor for v3. So in the current test-release, [v3.0.0-beta.2](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v3.0.0-beta.2), the Page- and Media-object is exposed to the template if the image is determined to be local.

I'll leave it in beta for some days or a week, in case any errors pop up.
