### ISSUE TITLE
Image paths on modular pages are absolute

### ISSUE THREAD

**Issue by jlehtinen** [OleVik/grav-plugin-imgcaptions#17]
Seems like since Grav v1.4, image paths on modular pages are converted to absolute values, so paths such as `../images/img1.jpg` are converted to `http://localhost:5757/../images/img1.jpg`.

**Comment by OleVik** [comment]
Does this affect how image paths are rendering by the plugin?

**Comment by jlehtinen** [comment]
Sorry – that’s what I meant. When the plugin is disabled, image paths are rendered correctly. As far as I tested, this only happens on modular pages.

**Comment by OleVik** [comment]
I'll test out some modulars to see what's happening.

**Comment by OleVik** [comment]
Testing with [Grav v1.4.5](https://github.com/getgrav/grav/tree/1.4.5), in Quark using [this content](https://github.com/getgrav/grav-skeleton-onepage-site/tree/develop/pages/01.home), I can replicate the issue with image pathing. The problem appears to be how image paths are interpreted in modulars, which happens when modulars are processed into HTML.

To resolve this, the plugin must run in HTML-mode or use the `onPageContentProcessed` as an override in Markdown-mode. Combine that with an absolute or local (in page-folder) path to the image, and the URL will be correct. I am considering how to allow for modulars-exceptions by using per-page-configs, but as it stands the plugins config and processing happens too early to allow this.
