### ISSUE TITLE
Links (media action) are embedding more of the html than expected

### ISSUE THREAD

**Issue by Lamecarlate** [OleVik/grav-plugin-imgcaptions#36]
Hello,

it seems that there is a problem between imgcaptions and link attributes… I know several issues are already there (#16 , #13 ) but my problem is different: the created link embeds the figure (which is good) but does not stop and embeds all elements afterwards, except another link.

I made a little test case, visible here: https://test.lamecarlate.net/test-caption.

The markdown is:

```markdown
There is the picture of a dog

![Dog](91e5f962-4ab5-4040-bcdb-153a9fee3c19.jpg?link "Smol black dog")

And of a landscape

![Cello](572509_700b_v1.jpg "Cello landscape")
```
And I added a bit of css to help visualise figures (solid red border) and links (dashed blue border). You can see there is a link on the first figure, and the next paragraph, and the next figure (the second image doesn't have a link, for this test' purpose).

Any idea of what could fix this? Thanks a lot!

- Grav version: v1.7.37.1
- plugin version: v3.2.0

Note: I tested without imgcaptions plugin, the link embedding is correct. I also tested with imgcaptions plugin and all other plugins disabled, the error is present.

**Comment by OleVik** [comment]
I'm afraid that certain such [media-actions](https://learn.getgrav.org/17/content/media#actions), unique to Grav, will not be supported. Once that messes up the regular expression engine (Regex), other HTML may suffer. Several alternative approaches exist:

- Wrap the image-reference in a link-reference, producing Markdown-compliant syntax and output, eg. `[![Cello](572509_700b_v1.jpg "Cello landscape")](572509_700b_v1.jpg)` ([explainer](https://meta.stackexchange.com/a/38917))
- Create a link to the image using JavaScript
- The [Image Captions](https://github.com/trilbymedia/grav-plugin-image-captions)-plugin could produce different results, as it uses a DOM-builder rather than Regex to build the code

**Comment by Lamecarlate** [comment]
OK, thanks for your response, I'll try this other plugin. If it works, I'll choose it over yours, sorry (but, apart from my precise need here, yours is very good and I liked it, thanks again).
