### ISSUE TITLE
Plugin image processing breaks when two items are close within div or paragraph

### ISSUE THREAD

**Issue by aitoraroza** [OleVik/grav-plugin-imgcaptions#4]
Hello,

I'm glad with your plugin so far and works as expected. Just what I needed ;) But suddenly a whole page went blank. I was just using markdown call for images, not title nor alt. Just images. I've looked into it by testing a Grav fresh install (last version) with just imgcaptions plugin. And it's reproducible.

Whenever two images are together, or within a div, or close to another processing markdown or twig (e.g. audio call) or next to a html tag image markdown stops working. Examples:

```
<div class="whatever" markdown="1">
![](image.jpg) {.class}
![](image.jpg) {.class}
![](image.jpg) {.class}
</div>
```

```
![](image.jpg) {.class}
![music.mp3](music-file.mp3) {.class}

```
`![](image.jpg)<br />`

I figured out that they need to be "alone" and really had to have images and embeds really close for design purposes. Placing them inside **span** or **div** solves this problem while keeping design into its place. 

`<span>![](image.jpg)</span>`

Just to let you know. And thanks for your piece of work!

**Comment by OleVik** [comment]
Thank you for notifying me, the problem is really with HTML: Images can be used as both block-elements and inline-elements, but by default they are treated as blocks. Your solution of wrapping the image with an inline element, which `<span>`s are by default, is optimal as the plugin can still wrap the image in the `figure`-element, resulting in this structure:

````
<span>
  <figure>
    <img />
    <figcaption></figcaption>
  </figure>
</span>
```

There was another, previous issue with inlining the Markdown image, and the solution also was inserting plain HTML. Markdown is not well-equipped to differentiate between various uses of images, as it's syntax is rather simple. Thus, wrapping the image for inline or other uses is the simplest solution.
